#!/bin/bash


(while read -r node;
do
        ctmserver=`echo $node |awk '{print $1}'`
        Agent=`echo $node |awk '{print $2}'`
        Nodegrp=jalitest

#list existing nodegroups for the Control-M Server
        existingnodegrp=`ctm config server:hostgroups::get $ctmserver|grep $Nodegrp`



#check if Agent is already part of the nodegroup
        ctm config server:hostgroup:agents::get $ctmserver $Nodegrp | grep "host" | awk '{print $2}' | sed -e 's/"//g' > existingnodes.txt
        if grep -Fxq "$Agent" existingnodes.txt
        then
                echo "Agent $Agent is already part of nodegroup $Nodegrp"
        else
                ctm config server:hostgroup:agent::add $ctmserver $Nodegrp $Agent
        fi
done) < /controlm/emsrv90/NivTesting/source.txt
